version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html  # Mount seluruh folder proyek
    networks:
      - my-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: fp_web
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql  # Impor file SQL
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
